PatientHandlingSystem/PatientHandlingSystem/Models/Tree.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PatientHandlingSystem.Models
{
    public class Tree
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }
}

PatientHandlingSystem/PatientHandlingSystem/Controllers/TreesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PatientHandlingSystem.DAL;
using PatientHandlingSystem.Models;
using PatientHandlingSystem.ViewModels;
using System.Diagnostics;

namespace PatientHandlingSystem.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class TreesController : Controller
    {
        private PatientHandlingContext db;
        private ITreeRepository treeRepository;

        public TreesController()
        {
            db = new PatientHandlingContext();
            treeRepository = new TreeRepository(db);
        }

        public TreesController(PatientHandlingContext context, ITreeRepository dataService)
        {
            db = context;
            this.treeRepository = dataService;
        }

        public ActionResult Index()
        {
            return View(db.Trees.ToList());
        }

        public ActionResult ViewTree(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tree tree = db.Trees.Find(id);
            if (tree == null)
            {
                return HttpNotFound();
            }
            ViewBag.TreeName = tree.Name;
            return View("ViewTree", "_TreeEditor", db.Nodes.Where(i=>i.TreeID == tree.ID).OrderBy(i=>i.ID).ToList());
        }

        public ActionResult Create()
        {
            var treeEditorVM = treeRepository.CreateTreeEditorViewModel();
            return View("Create", "_TreeEditor", treeEditorVM);
        }

        [ValidateInput(false)]
        public PartialViewResult UpdateTree(TreeEditorViewModel treeCreatorVM, string deleteButton)
        {
            List<Node> originalNodes = db.Nodes.Where(i => i.TreeID == treeCreatorVM.Tree.ID).OrderBy(j=>j.ID).ToList();
            //check if a node is selected, returning an error if its the first node
            if(treeCreatorVM.ParentNodeID == null && originalNodes.Count>0)
            {
                ModelState.AddModelError("NoNodeSelected", "Please select a node");
                return PartialView("_Tree", originalNodes);
            }
            //check if users is trying to delete a node and a stub node is selected
            else if (deleteButton == "true" && originalNodes.SingleOrDefault(i => i.ID == int.Parse(treeCreatorVM.ParentNodeID)).NodeValue == 0)
            {
                ModelState.AddModelError("StubNodeSelected", "Cannot delete a stub node");
                return PartialView("_Tree", originalNodes);
            }
            //return an error if the users has clicked on a parent node and is trying to submit a node. Exception to this being if this is the first node in the tree
            else if(deleteButton == null && originalNodes.Count>0)
            {
                Boolean leafNode = treeRepository.IsLeafNode(int.Parse(treeCreatorVM.ParentNodeID), treeCreatorVM.Tree.ID);
                if (leafNode == false)
                {
                    ModelState.AddModelError("StubNodeSelected", "Cannot insert a node in selected location");
                    return PartialView("_Tree", originalNodes);
                }
            }


            if (deleteButton == "true")//when delete button is pressed
            {
                var node = originalNodes.Single(i => i.ID == int.Parse(treeCreatorVM.ParentNodeID));
                if(node.SolutionNode)
                {
                    treeRepository.DeleteSolutionNode(treeCreatorVM.Tree.ID, treeCreatorVM.ParentNodeID);
                    treeRepository.Save();
                }
                else
                {
                    treeRepository.DeleteRegularNode(treeCreatorVM.Tree.ID, treeCreatorVM.ParentNodeID);
                }
            }
            else if(treeCreatorVM.NodeType == "Solution")//when user is trying to input a solution node
            {
                treeRepository.EnterSolutionNode(treeCreatorVM.ParentNodeID, treeCreatorVM.Tree.ID, treeCreatorVM.Solution, treeCreatorVM.SolutionTitle);
            }
            else if(treeCreatorVM.NodeType == "Equipment")
            {
                treeRepository.EnterEquipmentNode(treeCreatorVM.ParentNodeID, treeCreatorVM.SelectedEquipment.ID, treeCreatorVM.SelectedEquipmentAttribute.ID, treeCreatorVM.Tree.ID);
            }
            else //when user is trying to input a regular node, numeric or otherwise
            {
                treeRepository.EnterAttributeNode(treeCreatorVM.ParentNodeID, treeCreatorVM.SelectedPatientAttribute.ID, treeCreatorVM.Tree.ID, treeCreatorVM.SelectedPatientAttribute.Numeric, treeCreatorVM.SelectedPatientAttributeNumericValue.Value);
            }

            List<Node> nodes = db.Nodes.Where(i => i.TreeID == treeCreatorVM.Tree.ID).OrderBy(j => j.ID).ToList();

            return PartialView("_Tree", nodes);
        }

        public PartialViewResult DeleteNode(int nodeId, int treeId)
        {
            var dataService = new TreeRepository(db);
            dataService.IsLeafNode(nodeId, treeId);
            return PartialView("_Tree", db.Nodes.Where(i => i.TreeID == treeId).ToList());
        }

        // POST: Trees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken] this has to be removed because of the ajax call
        public ActionResult AddTreeName(string treeName)
        {
            var tree = db.Trees.Single(i=>i.ID == db.Trees.Max(j=>j.ID));
            tree.Name = treeName;
            db.Entry(tree).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public void EditTreeName(Tree postedTree)
        {
            var tree = db.Trees.Find(postedTree.ID);
            tree.Name = postedTree.Name;
            db.Entry(tree).State = EntityState.Modified;
            db.SaveChanges();
        }
        // GET: Trees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tree tree = db.Trees.Find(id);
            if (tree == null)
            {
                return HttpNotFound();
            }

            var treeEditorVM = treeRepository.GetTreeEditorViewModel(tree.ID);
            return View("Edit", "_TreeEditor", treeEditorVM);
        }

        // GET: Trees/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tree tree = db.Trees.Find(id);
            if (tree == null)
            {
                return HttpNotFound();
            }
            return View(tree);
        }

        // POST: Trees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tree tree = db.Trees.Single(i=>i.ID ==id);
            var nodes = db.Nodes.Where(i => i.TreeID == tree.ID).ToList();
            var solutions = db.Solutions.Where(i => i.TreeID == tree.ID).ToList();

            db.Trees.Remove(tree);
            db.Nodes.RemoveRange(nodes);
            db.Solutions.RemoveRange(solutions);

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PatientHandlingSystem/PatientHandlingSystem/Views/Trees/Create.cshtml
@model PatientHandlingSystem.ViewModels.TreeEditorViewModel

@{
    ViewBag.Title = "Create";
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<script src="~/Scripts/tinymce/tinymce.js"></script>
<script>
  tinymce.init({
      selector: '#Solution',
      width: 300,
      height: 300,
      plugins: ['link image media preview'],
      toolbar1: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media preview',
  });
</script>

<h2 class="text-center">Create Tree</h2>


<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">
            @using (Ajax.BeginForm("UpdateTree", "Trees", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "treeDiv" }))
            {
                <div class="container">

                    @*Display a selection panel for choosing which divs (equipment/pattient attribute/solution) to show/hide *@
                    <div class="row" id="selectionDiv">
                        <div class="col-md-12" style="font-weight:bold;">
                            @Html.RadioButtonFor(i => i.NodeType, "Solution", new { @class = "solutionTab" }) Solution
                            @Html.RadioButtonFor(i => i.NodeType, "PatientAttribute", new { @class = "attributeTab", @checked = "checked" }) Attribute
                            @Html.RadioButtonFor(i => i.NodeType, "Equipment", new { @class = "equipmentTab" }) Equipment
                        </div>
                    </div>

                    @*The patient attribute panel*@
                    <div class="row attribute top-buffer">
                        <div class="col-md-12">
                            @Html.HiddenFor(i => i.Tree.ID)
                            @Html.DropDownListFor(i => Model.SelectedPatientAttribute.ID, new SelectList(Model.PatientAttributes, "ID", "Name"), htmlAttributes: new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="row numericInput top-buffer">
                        <div class="col-md-12">
                            @Html.EditorFor(i => Model.SelectedPatientAttributeNumericValue.Value, new { htmlAttributes = new { @class = "numericInput form-control" } })
                        </div>
                    </div>
                    <div class="row attribute top-buffer">
                        <div class="col-md-12">
                            <button class="btn btn-default">Insert Node</button>
                        </div>
                    </div>

                    @*The equipment panel*@
                    <div class="row equipment top-buffer">
                        <div class="col-md-12">
                            @Html.Label("Equipment")
                        </div>
                    </div>
                    <div class="row equipment">
                        <div class="col-md-12">
                            @Html.HiddenFor(i => i.Tree.ID)
                            @Html.DropDownListFor(i => Model.SelectedEquipment.ID, new SelectList(Model.Equipment, "ID", "Name"), htmlAttributes: new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="row equipment top-buffer equipmentAttributeLabel">
                        <div class="col-md-12">
                            @Html.Label("Attribute")
                        </div>
                    </div>
                    <div class="row equipment top-buffer">
                        <div class="col-md-12">
                            <button class="btn btn-default">Insert Equipment Node</button>
                        </div>
                    </div>

                    @*the solution panel*@
                    <div class="row solution top-buffer">
                        <div class="col-md-12 form-group">
                            @Html.EditorFor(i => i.SolutionTitle, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>
                    <div class="row solution top-buffer">
                        <div class="col-md-12 form-group">
                            @Html.TextAreaFor(i => i.Solution, new { @rows = "20", @placeholder = "Enter solution", @class = "form-control", style = "" })
                        </div>
                    </div>
                    <div class="row solution">
                        <div class="col-md-12">
                            <input type="submit" value="Insert Solution" class="btn btn-default">
                        </div>
                    </div>

                    @*the delete node button*@
                    <div class="row top-buffer">
                        <div class="col-md-12">
                            <button class="btn btn-danger" id="button" name="deleteButton" value="true">Delete</button>
                        </div>
                    </div>
                </div>
            }
        </div>
        <div id="treeDiv" class="col-md-9">
            @Html.Partial("_Tree", Model.Nodes)
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        //show or hide the attribute or solution tab depending on the radio button that is selected
        $(".solution").hide();
        $(".equipment").hide();
        $("#selectionDiv").click(function () {
            if ($(".attributeTab").is(":checked")) {
                $(".attribute").show();
                $(".solution").hide();
                $(".equipment").hide();
            }
            else if ($(".solutionTab").is(":checked")) {
                $(".solution").show();
                $(".attribute").hide();
                $(".numericInput").hide();
                $(".equipment").hide();
            }
            else {
                $(".equipment").show();
                $(".solution").hide();
                $(".attribute").hide();
                $(".numericInput").hide();
            }
        });

    //add all numeric ids to an array
        var numericIds = [];
        @foreach (var a in Model.PatientAttributes)
        {
            if(a.Numeric)
            {
                @:numericIds.push(@a.ID);
            }
        }


        $(".numericInput").hide();

    //when a different dropdownlist selection is made, check to see if it is a numeric attribute, and if it is, display the numeric input box
        $("#SelectedPatientAttribute_ID").change(function () {
            var numericAttribute = false;
            for (var i = 0; i < numericIds.length; i++) {
                if (numericIds[i] == $(this).val()) {
                    console.log("numeric");
                    $(".numericInput").show();
                    $(this).after("<input id='SelectedPatientAttribute_Numeric' name='SelectedPatientAttribute.Numeric' type='hidden' value='true' />");
                    numericAttribute = true;
                }
            }
            if(numericAttribute == false) {
                $(".numericInput").hide();
                $("#SelectedAttribute_Numeric").remove();
            }

        });

    //enter and post the tree name
        var tree_Name = prompt("Enter tree name");
        $.post("/Trees/AddTreeName", { "treeName": tree_Name });
    



        //populate the attribute drop down list when the equipment drop down list changes
        var equipmentAttributes = [];
        @foreach(var attribute in Model.EquipmentAttributes)
        {
            @:var equipmentAttribute = { id: 0, name: "", equipmentId: 0 };
            @:equipmentAttribute.id = @attribute.ID;
            @:equipmentAttribute.name = '@attribute.Name';
            @:equipmentAttribute.equipmentId= '@attribute.EquipmentID';
            @:equipmentAttributes.push(equipmentAttribute);
        }

        insertEquipmentAttributeDropDown($("#SelectedEquipment_ID").val(), equipmentAttributes);

        $("#SelectedEquipment_ID").on('change', function(){
            insertEquipmentAttributeDropDown(this.value, equipmentAttributes);
        });

        //takes the id of the currently selected equipment attribute and the list of equipment attributes (objects containing their text and ids)
        function insertEquipmentAttributeDropDown(equipmentAttributeValue, equipmentAttributes){
            var selectedEquipmentAttributes = [];
            for(var i=0; i<equipmentAttributes.length; i++){
                if(equipmentAttributes[i].equipmentId == equipmentAttributeValue){
                    selectedEquipmentAttribute = {id: equipmentAttributes[i].id, name:equipmentAttributes[i].name };
                    selectedEquipmentAttributes.push(selectedEquipmentAttribute);
                }
            }
            var optionsString = "";
            for(var i=0; i<selectedEquipmentAttributes.length; i++){
                optionsString +="<option value='"+selectedEquipmentAttributes[i].id+"'>"+selectedEquipmentAttributes[i].name+"</option>";
            }

            //string containing the options for the dropdownlist
            $(".equipmentAttributeLabel").last().html(
            "<div class='col-md-1'>"+
            "<label for='Attribute'>Attribute</label>"+    
            "</div>"+
            "<div class='col-md-12'>"+
                "<select class='form-control' id='SelectedEquipmentAttribute_ID' name='SelectedEquipmentAttribute.ID'>"+
                    optionsString+
                "</select>"+
            "</div>"
            );
        };
    });

</script>

PatientHandlingSystem/PatientHandlingSystem/Views/Trees/Delete.cshtml
@model PatientHandlingSystem.Models.Tree

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tree</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PatientHandlingSystem/PatientHandlingSystem/Views/Trees/Edit.cshtml
@model PatientHandlingSystem.ViewModels.TreeEditorViewModel

@{
    ViewBag.Title = "Edit";
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<script src="~/Scripts/tinymce/tinymce.js"></script>
<script>
  tinymce.init({
      selector: '#Solution',
      width: 300,
      height: 300,
      plugins: ['link image media preview'],
      toolbar1: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media preview',
  });
</script>

<h2 class="text-center"><span id="title">@Model.Tree.Name</span> <button class="btn btn-sm" id="editName">Edit Name</button></h2>

<br />
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">
            @using (Ajax.BeginForm("UpdateTree", "Trees", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "treeDiv" }))
            {
                <div class="container">

                    @*Display a selection panel for choosing which divs (equipment/pattient attribute/solution) to show/hide *@
                    <div class="row" id="selectionDiv">
                        <div class="col-md-12" style="font-weight:bold;">
                            @Html.RadioButtonFor(i => i.NodeType, "Solution", new { @class = "solutionTab" }) Solution
                            @Html.RadioButtonFor(i => i.NodeType, "PatientAttribute", new { @class = "attributeTab", @checked = "checked" }) Attribute
                            @Html.RadioButtonFor(i => i.NodeType, "Equipment", new { @class = "equipmentTab" }) Equipment
                        </div>
                    </div>

                    @*The patient attribute panel*@
                    <div class="row attribute top-buffer">
                        <div class="col-md-12">
                            @Html.HiddenFor(i => i.Tree.ID)
                            @Html.DropDownListFor(i => Model.SelectedPatientAttribute.ID, new SelectList(Model.PatientAttributes, "ID", "Name"), htmlAttributes: new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="row numericInput top-buffer">
                        <div class="col-md-12">
                            @Html.EditorFor(i => Model.SelectedPatientAttributeNumericValue.Value, new { htmlAttributes = new { @class = "numericInput form-control" } })
                        </div>
                    </div>
                    <div class="row attribute top-buffer">
                        <div class="col-md-12">
                            <button class="btn btn-default">Insert Node</button>
                        </div>
                    </div>

                    @*The equipment panel*@
                    <div class="row equipment top-buffer">
                        <div class="col-md-12">
                            @Html.Label("Equipment")
                        </div>
                    </div>
                    <div class="row equipment">
                        <div class="col-md-12">
                            @Html.HiddenFor(i => i.Tree.ID)
                            @Html.DropDownListFor(i => Model.SelectedEquipment.ID, new SelectList(Model.Equipment, "ID", "Name"), htmlAttributes: new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="row equipment top-buffer equipmentAttributeLabel">
                        <div class="col-md-12">
                            @Html.Label("Attribute")
                        </div>
                    </div>
                    <div class="row equipment top-buffer">
                        <div class="col-md-12">
                            <button class="btn btn-default">Insert Equipment Node</button>
                        </div>
                    </div>

                    @*the solution panel*@
                    <div class="row solution top-buffer">
                        <div class="col-md-12 form-group">
                            @Html.EditorFor(i => i.SolutionTitle, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>
                    <div class="row solution top-buffer">
                        <div class="col-md-12 form-group">
                            @Html.TextAreaFor(i => i.Solution, new { @rows = "20", @placeholder = "Enter solution", @class = "form-control", style = "" })
                        </div>
                    </div>
                    <div class="row solution">
                        <div class="col-md-12">
                            <input type="submit" value="Insert Solution" class="btn btn-default">
                        </div>
                    </div>

                    @*the delete node button*@
                    <div class="row top-buffer">
                        <div class="col-md-12">
                            <button class="btn btn-danger" id="button" name="deleteButton" value="true">Delete</button>
                        </div>
                    </div>
                </div>
            }
        </div>
        <div id="treeDiv" class="col-md-9">
            @Html.Partial("_Tree", Model.Nodes)
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        //show or hide the attribute or solution tab depending on the radio button that is selected
        $(".solution").hide();
        $(".equipment").hide();
        $("#selectionDiv").click(function () {
            if ($(".attributeTab").is(":checked")) {
                $(".attribute").show();
                $(".solution").hide();
                $(".equipment").hide();
            }
            else if ($(".solutionTab").is(":checked")) {
                $(".solution").show();
                $(".attribute").hide();
                $(".numericInput").hide();
                $(".equipment").hide();
            }
            else {
                $(".equipment").show();
                $(".solution").hide();
                $(".attribute").hide();
                $(".numericInput").hide();
            }
        });

    //add all numeric ids to an array
        var numericIds = [];
        @foreach (var a in Model.PatientAttributes)
        {
            if(a.Numeric)
            {
                @:numericIds.push(@a.ID);
            }
        }


        $(".numericInput").hide();

    //when a different dropdownlist selection is made, check to see if it is a numeric attribute, and if it is, display the numeric input box
        $("#SelectedPatientAttribute_ID").change(function () {
            var numericAttribute = false;
            for (var i = 0; i < numericIds.length; i++) {
                if (numericIds[i] == $(this).val()) {
                    console.log("numeric");
                    $(".numericInput").show();
                    $(this).after("<input id='SelectedPatientAttribute_Numeric' name='SelectedPatientAttribute.Numeric' type='hidden' value='true' />");
                    numericAttribute = true;
                }
            }
            if(numericAttribute == false) {
                $(".numericInput").hide();
                $("#SelectedAttribute_Numeric").remove();
            }

        });

        //edit name of tree
        $("#editName").click(function () {
            var tree_Name = prompt("Enter tree name", '@Model.Tree.Name');
            $.post("/Trees/EditTreeName", { "ID": @Model.Tree.ID, "Name": tree_Name });
            $("#title").text(tree_Name)
        });

        //populate the attribute drop down list when the equipment drop down list changes
        var equipmentAttributes = [];
        @foreach(var attribute in Model.EquipmentAttributes)
        {
            @:var equipmentAttribute = { id: 0, name: "", equipmentId: 0 };
            @:equipmentAttribute.id = @attribute.ID;
            @:equipmentAttribute.name = '@attribute.Name';
            @:equipmentAttribute.equipmentId= '@attribute.EquipmentID';
            @:equipmentAttributes.push(equipmentAttribute);
        }

        insertEquipmentAttributeDropDown($("#SelectedEquipment_ID").val(), equipmentAttributes);

        $("#SelectedEquipment_ID").on('change', function(){
            insertEquipmentAttributeDropDown(this.value, equipmentAttributes);
        });

        //takes the id of the currently selected equipment attribute and the list of equipment attributes (objects containing their text and ids)
        function insertEquipmentAttributeDropDown(equipmentAttributeValue, equipmentAttributes){
            var selectedEquipmentAttributes = [];
            for(var i=0; i<equipmentAttributes.length; i++){
                if(equipmentAttributes[i].equipmentId == equipmentAttributeValue){
                    selectedEquipmentAttribute = {id: equipmentAttributes[i].id, name:equipmentAttributes[i].name };
                    selectedEquipmentAttributes.push(selectedEquipmentAttribute);
                }
            }
            var optionsString = "";
            for(var i=0; i<selectedEquipmentAttributes.length; i++){
                optionsString +="<option value='"+selectedEquipmentAttributes[i].id+"'>"+selectedEquipmentAttributes[i].name+"</option>";
            }

            //string containing the options for the dropdownlist
            $(".equipmentAttributeLabel").last().html(
            "<div class='col-md-1'>"+
            "<label for='Attribute'>Attribute</label>"+    
            "</div>"+
            "<div class='col-md-12'>"+
                "<select class='form-control' id='SelectedEquipmentAttribute_ID' name='SelectedEquipmentAttribute.ID'>"+
                    optionsString+
                "</select>"+
            "</div>"
            );
        };
    });
</script>

PatientHandlingSystem/PatientHandlingSystem/Views/Trees/Index.cshtml
@model IEnumerable<PatientHandlingSystem.Models.Tree>

@{
    ViewBag.Title = "Trees";
}

<h2>Trees</h2>

<p>
    @Html.ActionLink("Create New Tree", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("View Tree", "ViewTree", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>